---
title: "Logicals"
author: "Connor Flynn"
date: "8/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Taking a look at `starwars`

- `include = ` : show or hide everything
- `echo = ` : show or hide code
- `summary(data) = ` : summarize data

```{r, warning = FALSE}


ggplot(data = starwars, aes(x = height, y = mass))+
  geom_point(color = "purple")



```

## Find the mean, variance, and standar deviation of character height

```{r}
sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_mean


# Variance of character height (var())
variance_height <- var(starwars$height, na.rm = TRUE)

# Standard Deviation of height

dev_sw_height <- sd(starwars$height, na.rm = TRUE)
dev_sw_height
```

## Logical Expressions


```{r}

5 < 10

"cat" < "armadillo"

"cat" < "elephant"

"dog" == "dog"

```



```{r}
10 < 11

3 <= 1
```
```{r}
tarantulas <- c(1,3,7,10,15)

tarantulas > 5


```


## Logical operators 

- `!`
- `&`
_ `|` 

```{r}

3 < 1 | 8 > 2


6 < 10 & 5 < 1

7!= 11
# is seven not equal to eleven

4 != 4 | 2 <5 | 6 > 10

0 == FALSE

1 == TRUE



```



